name: Build and Test Android App

on:
  push:
    branches:
      - main

env:
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: actions/setup-android@v1
      with:
        android-sdk-version: 30
        licenses: 'android-sdk-preview-license-52d11cd2'

    - name: Build Android App
      run: ./gradlew assembleDebug

    - name: Test Android App
      run: ./gradlew test