name: Android CI Pipeline
on:
  push:
     branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out into mobile-app repo
        uses: actions/checkout@v3
      
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Yarn
        run: sudo npm install --global yarn

      - name: Install Dependecies
        run: yarn install
      
      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Prettier
        run: yarn prettier
    
      - name: Lint
        run: yarn lint
      
      - name: Unit testing
        run: yarn test -u
  
      - name: Sonarqube
        run: yarn sonar   